# Generated by Django 4.2.2 on 2023-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendance_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
