# Generated by Django 4.2.2 on 2023-07-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_attendance_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
    ]
